services:
  - type: web
    name: see-music
    env: node
    plan: free
    buildCommand: npm install && (python3 -m pip install --user yt-dlp || true)
    startCommand: npm run start
    envVars:
      - key: HOST
        value: 0.0.0.0
